hydra:
  run:
    dir: .
  output_subdir: null
  job:
    chdir: false
trainings_artifacts:
  training_cfg_path: /davinci-1/work/protezionecivile/RADMET_MODELS/ConvLSTM/config_used.yaml
  checkpoint_path: /davinci-1/work/protezionecivile/RADMET_MODELS/ConvLSTM/epoch=56-CriticalSuccessIndex_10=0.25.ckpt
transforms:
  0:
    name: LogarithmicTransform
    args:
      threshold: 0.2
    adjust:
    - threshold
  1:
    name: MinMaxNormalize
    args:
      excluded_value: -9999
      input_min: 0.0
      input_max: 300.0
      output_min: 0.0
      output_max: 1.0
    adjust:
    - input_min
    - input_max
    - excluded_value
windows_extraction_args:
  hdf_key: /dataset1/data1/data
  lead_time: 12
  wlen: 12
  stride: 1
  interval_minutes: 5

dataframe_strategy:
  input:
    name: from_hdf_folder
    args:
      data_folder: /davinci-1/work/protezionecivile/data
      datetime_format: '%d-%m-%Y-%H-%M'
      fallback_folder: /davinci-1/work/protezionecivile/data1/SRI_adj

  slicers:
    - name: start_end
      args:
        start_dt: "2025-11-22 20:00:00"
        end_dt: "2025-11-22 20:50:00"

    - name: continuity
      args:
        freq: 5min
        fill: true
        max_gap_frames: 3
save_path: /davinci-1/work/protezionecivile/nwc_webapp/real_time_results/ConvLSTM
save_npz: false
save_npy: true
